version: "3.3"
services:
  extendalo:
    restart: unless-stopped
    # build with this directory's Dockerfile
    build: .
    # this specifies the tag
    image: extendalo:latest

    volumes:
      - ./extendalo-persist:/app/extendalo-persist
    env_file:
      - .env
